name: Asynccalls Daily Deploy

on:
  push:
    paths:
      - asynccalls/**
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  deploy-asynccalls:
    defaults:
      run:
        working-directory: ./deprecated/asynccalls/contracts/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./deprecated/asynccalls/contracts/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          if npm run deploy | grep -q "Contract deployed"; then
            echo "Contract successfully deployed!"
          else
            echo "Failed to deploy contract ..."
            exit 1
          fi
        env:
          JSON_RPC_URL_PUBLIC: ${{ secrets.JSON_RPC_URL_PUBLIC }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
